Sprint3/step 1
Denwer81/react-burger pull request #5
Opened 2022-11-03 10:42 UTC by Denwer81

add all feature

2022-11-03 15:52 UTC, randomroot requested changes
**Доброго времени суток!**

Вы проделали **отличную** работу, очень много **крутых и удобных** хуков, **корректная** работа со редакс-стором и **правильно** построенная схема роутинга в приложении, есть **уведомления** пользователя об ошибках и **красивые** анимации, **так держать** 👍 

Тем не менее, для успешной сдачи работы, вам **необходимо** внимательно изучить комментарии в ревью, обратив **особое внимание** на следующие моменты:

**Нужно исправить:**

- После успешной авторизации следует **переадресовывать** пользователя на тот маршрут, к которому пользователь не получил доступ ранее. Например, при переходе по прямой ссылке на `/profile` после логина следует открывать страницу профиля;
- В данный момент **нет возможности** отправить форму пользователя без ввода пароля в поле. Следует сделать это поле необязательным, т.к. пользователь должен иметь возможность изменить просто имя или адрес электронной почты :)
- В списке ингредиентов следует отображать **счетчик у булок** со значением 2, т.к. добавляются две копии ингредиента в заказ (https://disk.yandex.ru/i/JHeJi2tsUEVtzg);
- У компонента `ModalOverlay` не должно быть `children`, т.к. он служит **подложкой** под модальным окном, а не контейнером с его содержимым;
- Следует задать **время жизни токена** с помощью параметра `Expires`, т.к. на данный момент он автоматически выставляется в `Session`, что означает его удаление после закрытия браузера. Пользователя может быть неудобно осуществлять повторную авторизацию при каждом запуске. Пример выставляемого времени вы можете найти, если скопируете ваш авторизационный токен в форму на https://jwt.io (искомое значение - разница между `iat` и `exp`).

**Можно улучшить:**

- Хорошо, что у вас реализован механизм проверки и обновления токена, однако имеет смысл в нём ориентироваться не на текст сообщения об ошибке, а на **код ответа** - если он = 403, значит токен протух и его необходимо обновить;
- В работе сейчас немало строк с **логгированием**, рекомендуется их свести к минимуму после завершения отладки проекта, чтобы консоль поддерживалась в чистоте :)

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**.

---

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-03 15:52 UTC, randomroot commented on src/utils/handleCookie.js
> +function setCookie(name, value, props) {
🟡 **Можно улучшить:**

Лучше задавать параметр `Path` у кукисов равный корню `/`, чтобы исключить вероятность дублирования нескольких кукисов с одним и тем же именем, что при извлечении может привести к неприятным последствиям (например будет извлечен `undefined`)

2022-11-03 15:52 UTC, randomroot commented on src/utils/handleFetch.js
> +  return response.json();
🔴 **Нужно исправить:**

Не следует убирать проверку на `res.ok`, т.к. ошибка вылетит в `catch` только, если возникли проблемы на уровне браузера (например нет сети), а если сервер вернет ошибку, то реакции не последует. Аналогично выше в методе `checkResponseRedux`

2022-11-03 15:52 UTC, randomroot commented on src/services/hooks/useAuth.js
> +          if (res.payload.message === 'jwt expired')
🟡 **Можно улучшить:**

Текст ошибки может измениться со временем, однако код 403, свидетельствующий об окончании действия токена - маловероятно, поэтому лучше ориентироваться именно на код ответа

2022-11-03 15:52 UTC, randomroot commented on src/services/hooks/useAuth.js
> +    if (values.name && values.email && values.password) {
🔴 **Нужно исправить:**

Пользователю необязательно вводить пароль в форму, чтобы изменить значение "имени" и "эл. почты", т.к. работает метод `PATCH`, который осуществит замену только тех полей, которые изменились. Следует убрать проверку наличия значения `values.password`

2022-11-03 15:52 UTC, randomroot commented on src/services/slices/auth.js
> +        state.loadingStatus = 'loading';
🟡 **Можно улучшить:**

Значения статусов имеет смысл вынести в отдельный объект-константу и использовать его ключи здесь, чтобы удобно переиспользовать их и при необходимости изменять только в одном месте:
```js
const  REQUEST_STATUS = {
  loading: 'loading',
  ...
}

state.loadingStatus = REQUEST_STATUS.loading;
```

2022-11-03 15:52 UTC, randomroot commented on src/services/slices/order.js
> +        console.log(action.payload)
🟡 **Можно улучшить:**

Логгирование очень полезно на этапе разработки, однако, при сдаче работы следует эти моменты удалить из кода, чтобы в консоли было минимальное количество информационных сообщений и легче было отлавливать ошибки после "выхода в релиз" :)

Здесь и в рамках проекта.

2022-11-03 15:52 UTC, randomroot commented on src/components/Ui/SomethingWrong/SomethingWrong.js
> +        {error || "Попробуйте перегазругить страницу"}
🟡 **Можно улучшить:**

Допущена орфографическая ошибка

2022-11-03 15:52 UTC, randomroot commented on src/components/Ui/SomethingWrong/SomethingWrong.js
> +      <h2 className={'text text_type_main-medium mb-6'} style={{marginTop: 52}}>
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2022-11-03 15:52 UTC, randomroot commented on src/components/Ui/Modals/ModalOverlay/ModalOverlay.js
> +    <div className={styles.container}>
🔴 **Нужно исправить:**

Возможно, в рамках предыдущих спринтов не было отмечено, однако у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

2022-11-03 15:52 UTC, randomroot commented on src/components/Ui/Modals/Modal/Modal.js
> +// import useAnimation from '../../../../services/hooks/useAnimation';
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

Здесь и в рамках проекта

2022-11-03 15:52 UTC, randomroot commented on src/Pages/Register/Register.js
> +        <Button type="primary" size="medium" htmlType="submit">Зарегестрироваться</Button>
🟡 **Можно улучшить:**

Допущена орфографическая ошибка

2022-11-03 15:52 UTC, randomroot commented on src/Pages/ResetPassword/ResetPassword.js
> +          placeholder={'Введите коди из письма'}
🟡 **Можно улучшить:**

Возможно, здесь закралась небольшая ошибка в окончании слова "код" :)

2022-11-03 15:52 UTC, randomroot commented on src/components/IngredientDetails/IngredientDetails.js
> +    .filter((item) => item._id === params.ingredientId).at(0)
🟡 **Можно улучшить:**

Функцию `filter` в данном случае целесообразно заменить на `find` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find), т.к. её задача заключается именно в поиске нужного элемента в массиве без создания нового :)

2022-11-04 13:07 UTC, Denwer81 commented on src/utils/handleFetch.js
> +  return response.json();
В checkResponseRedux я проверяю if (response.status === 404), 
и прокидываю ошибку в rejectWithValue({ status: false, message:error.message }) // тут изменил чтобы в пейлоад приходило стандартизировано.
Далее при любых других исходах ответ сервера приходит res.payload, и я обрабатываю и rejected и fulfilled.
Я так сделал что бы достать все кастомные ошибки, если сразу проверить на res.ok то достать их нет возможности.
Переделал с res.ok и сейчас в reset password бек кидает status 404 когда вводишь не правильный логин или код из письма. Бек немного кривой.

У нас есть похожая тема в слаке, по этому вопросу. https://practicum-students.slack.com/archives/C042F6AG4G7/p1667390043170219

2022-11-04 13:10 UTC, Denwer81 commented on src/services/hooks/useAuth.js
> +          if (res.payload.message === 'jwt expired')
согласен, но как писал выше, у меня приходит payload уже к этому моменту. придется респонс писать отдельно для этого фетча.

2022-11-05 06:11 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли **практически все** необходимые изменения в ваш проект, однако осталось несколько важных моментов, которые следует также **добавить** для успешной сдачи работы:

- После успешной авторизации следует **переадресовывать** пользователя на тот маршрут, к которому пользователь не получил доступ ранее. Например, при переходе по прямой ссылке на /profile после логина следует открывать страницу профиля;
- Следует вынести **время жизни** токена в отдельную константу;

**Хороших вам выходных!** 🐈

2022-11-05 06:11 UTC, randomroot commented on src/services/hooks/useAuth.js
> +  setCookie('accessToken', res.payload.accessToken, { expires: 60 * 60 * 24 * 7, path: '/' });
🔴 **Нужно исправить:**

Следует вынести время жизни токена в отдельную константу

2022-11-05 07:32 UTC, Denwer81 commented
fixed.
Спасибо за ревью!
Хороших выходных.

2022-11-05 08:00 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-11-05 08:04 UTC, merged